### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by ftoledo** [ohadcn/snbopen#2]
Hi all i'm using python 2.7.12 on debian stretch:

<pre>
ragnarok@ragnarok:/tmp$ ./snbopen.py ./NuevaNota_03032016_170856.snb 
Traceback (most recent call last):
  File "./snbopen.py", line 146, in <module>
    snbToPdf(argv[1],pdfFileName)
  File "./snbopen.py", line 127, in snbToPdf
    addImage(snbFile,pdfCanvas,images[0],rels,element)
  File "./snbopen.py", line 37, in addImage
    img = Image.fromstring("RGBA",(width,height),imgStr[52:])
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2076, in fromstring
    "Please call frombytes() instead.")
NotImplementedError: fromstring() has been removed. Please call frombytes() instead.
</pre>

somebody can fix it?
thanks!

**Comment by ohadcn** [comment]
closed after accepting your pull request.
